package POJOS;
// Generated 31-mar-2024 14:13:27 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Recibos generated by hbm2java
 */
public class Recibos  implements java.io.Serializable {


     private int numeroRecibo;
     private Contribuyente contribuyente;
     private String nifContribuyente;
     private String direccionCompleta;
     private String nombre;
     private String apellidos;
     private Date fechaRecibo;
     private int lecturaAnterior;
     private int lecturaActual;
     private int consumom3;
     private Date fechaPadron;
     private double totalBaseImponible;
     private double totalIva;
     private double totalRecibo;
     private String iban;
     private String email;
     private String exencion;
     private Set lineasrecibos = new HashSet(0);

    public Recibos() {
    }

	
    public Recibos(int numeroRecibo, String nifContribuyente, String direccionCompleta, String nombre, String apellidos, Date fechaRecibo, int lecturaAnterior, int lecturaActual, int consumom3, Date fechaPadron, double totalBaseImponible, double totalIva, double totalRecibo) {
        this.numeroRecibo = numeroRecibo;
        this.nifContribuyente = nifContribuyente;
        this.direccionCompleta = direccionCompleta;
        this.nombre = nombre;
        this.apellidos = apellidos;
        this.fechaRecibo = fechaRecibo;
        this.lecturaAnterior = lecturaAnterior;
        this.lecturaActual = lecturaActual;
        this.consumom3 = consumom3;
        this.fechaPadron = fechaPadron;
        this.totalBaseImponible = totalBaseImponible;
        this.totalIva = totalIva;
        this.totalRecibo = totalRecibo;
    }
    public Recibos(int numeroRecibo, Contribuyente contribuyente, String nifContribuyente, String direccionCompleta, String nombre, String apellidos, Date fechaRecibo, int lecturaAnterior, int lecturaActual, int consumom3, Date fechaPadron, double totalBaseImponible, double totalIva, double totalRecibo, String iban, String email, String exencion, Set lineasrecibos) {
       this.numeroRecibo = numeroRecibo;
       this.contribuyente = contribuyente;
       this.nifContribuyente = nifContribuyente;
       this.direccionCompleta = direccionCompleta;
       this.nombre = nombre;
       this.apellidos = apellidos;
       this.fechaRecibo = fechaRecibo;
       this.lecturaAnterior = lecturaAnterior;
       this.lecturaActual = lecturaActual;
       this.consumom3 = consumom3;
       this.fechaPadron = fechaPadron;
       this.totalBaseImponible = totalBaseImponible;
       this.totalIva = totalIva;
       this.totalRecibo = totalRecibo;
       this.iban = iban;
       this.email = email;
       this.exencion = exencion;
       this.lineasrecibos = lineasrecibos;
    }
   
    public int getNumeroRecibo() {
        return this.numeroRecibo;
    }
    
    public void setNumeroRecibo(int numeroRecibo) {
        this.numeroRecibo = numeroRecibo;
    }
    public Contribuyente getContribuyente() {
        return this.contribuyente;
    }
    
    public void setContribuyente(Contribuyente contribuyente) {
        this.contribuyente = contribuyente;
    }
    public String getNifContribuyente() {
        return this.nifContribuyente;
    }
    
    public void setNifContribuyente(String nifContribuyente) {
        this.nifContribuyente = nifContribuyente;
    }
    public String getDireccionCompleta() {
        return this.direccionCompleta;
    }
    
    public void setDireccionCompleta(String direccionCompleta) {
        this.direccionCompleta = direccionCompleta;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public Date getFechaRecibo() {
        return this.fechaRecibo;
    }
    
    public void setFechaRecibo(Date fechaRecibo) {
        this.fechaRecibo = fechaRecibo;
    }
    public int getLecturaAnterior() {
        return this.lecturaAnterior;
    }
    
    public void setLecturaAnterior(int lecturaAnterior) {
        this.lecturaAnterior = lecturaAnterior;
    }
    public int getLecturaActual() {
        return this.lecturaActual;
    }
    
    public void setLecturaActual(int lecturaActual) {
        this.lecturaActual = lecturaActual;
    }
    public int getConsumom3() {
        return this.consumom3;
    }
    
    public void setConsumom3(int consumom3) {
        this.consumom3 = consumom3;
    }
    public Date getFechaPadron() {
        return this.fechaPadron;
    }
    
    public void setFechaPadron(Date fechaPadron) {
        this.fechaPadron = fechaPadron;
    }
    public double getTotalBaseImponible() {
        return this.totalBaseImponible;
    }
    
    public void setTotalBaseImponible(double totalBaseImponible) {
        this.totalBaseImponible = totalBaseImponible;
    }
    public double getTotalIva() {
        return this.totalIva;
    }
    
    public void setTotalIva(double totalIva) {
        this.totalIva = totalIva;
    }
    public double getTotalRecibo() {
        return this.totalRecibo;
    }
    
    public void setTotalRecibo(double totalRecibo) {
        this.totalRecibo = totalRecibo;
    }
    public String getIban() {
        return this.iban;
    }
    
    public void setIban(String iban) {
        this.iban = iban;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getExencion() {
        return this.exencion;
    }
    
    public void setExencion(String exencion) {
        this.exencion = exencion;
    }
    public Set getLineasrecibos() {
        return this.lineasrecibos;
    }
    
    public void setLineasrecibos(Set lineasrecibos) {
        this.lineasrecibos = lineasrecibos;
    }




}


